import { MongoClient } from 'mongodb'
import style from '@/styles/Home.module.css'
import Head from 'next/head'
import Editor from '@/components/Editor'
import Graph from '@/components/Graph'
import Task from '@/interfaces/task'

const Home: React.FC<{ tasks: Task[] }> = (props) => {
  return (
    <>
      <Head>
        <title>Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.content}>
        <Editor tasks={props.tasks}/>
        <Graph />
      </div>
    </>
  )
}

export async function getStaticProps() {
  const client = await MongoClient.connect(
    "mongodb+srv://poloman:stupido@cluster0.shuvold.mongodb.net/my_database?retryWrites=true&w=majority"
  );

  const db = client.db();

  const tasksCollection = db.collection("tasks");

  const tasks = (await tasksCollection.find().toArray()).map(task => ({
    text: task.text,
    start: task.start,
    end: task.end,
    id: task.id,
    isGhost: task.isGhost
  }));

  client.close();

  return { props: { tasks: tasks } };
}

export default Home;